### ISSUE TITLE
Server Error :  KeyError: 'save_diagram'

### ISSUE THREAD

**Issue by jimisens** [Maralai/draw.io#3]
Hi @Maralai !
I just installed your module in odoo 17.
I discovered draw.io recently and i am very excited by its functionality. And when I found your module I was very happy +2!

After installing it I receive the following error when pressing the "Save" button on a diagram. There seems to be a problem with the base_automation module: 

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1783, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1810, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2014, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 759, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base_automation/models/base_automation.py", line 744, in write
    old_values = {
  File "/usr/lib/python3/dist-packages/odoo/addons/base_automation/models/base_automation.py", line 745, in <dictcomp>
    record.id: {field_name: record[field_name] for field_name in vals}
  File "/usr/lib/python3/dist-packages/odoo/addons/base_automation/models/base_automation.py", line 745, in <dictcomp>
    record.id: {field_name: record[field_name] for field_name in vals}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6649, in __getitem__
    return self._fields[key].__get__(self, self.env.registry[self._name])
KeyError: 'save_diagram'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://crm.oove.blue/web/assets/2cd57bf/web.assets_web.min.js:2888:163)
        at XMLHttpRequest.<anonymous> (https://crm.oove.blue/web/assets/2cd57bf/web.assets_web.min.js:2892:13)

**Comment by Maralai** [comment]
Looks like the field name isn't in the registry. Please restart your odoo instance, upgrade the app and try again. LMK.
